### ISSUE TITLE
How to use CheckBox

### ISSUE THREAD

**Issue by Saber0517** [sdl/Testy#7]
Hi I try to ues Testy for extjs3 demo ass you guys provide in index.md page, but no matter how I try I just don't know how to use it 

`public Checkbox catRight = new Checkbox(this).setLabel("CatRight");`

I just don't know the basic usage rule of the extjs3 part

**Comment by Saber0517** [comment]
If you guys can provide some basic rule about when to set Label and When to set Label Position would be nice,I am trying to enrich the demo for extjs in [https://github.com/nmatei/cucumber-testy-tutorial](url)

**Comment by vculea** [comment]
Hello,

You need to know which version of ExtJS use, because the elements are different for each version.
Or if you can give me a URL from your application, I help to identify the exact item.

Success!

**Comment by vculea** [comment]
Yes, you are right. We know  that need more documentation. We’ll add more when we have time.

Viorel

**Comment by Saber0517** [comment]
@vculea  OK,  when you guys have time to enrich it please let me know ,I also can help to add the process and pic when I finish the extjs 3 demo.

**Comment by Saber0517** [comment]
>[https://rawgit.com/sdl/Testy/master/src/test/functional/app-demo/extjs/index.html](url)

if I want to locate the CatRight or CatLeft how to do it? 

I also wonder How to locate the DateFrom  

I try my best to read the source code .... but still need help

**Comment by vculea** [comment]
For this page:
https://rawgit.com/sdl/Testy/master/src/test/functional/app-demo/extjs/index.html

See example:

https://github.com/sdl/Testy/blob/master/src/test/functional/java/com/sdl/selenium/extjs3/form/CheckBoxIntegrationTest.java

https://github.com/sdl/Testy/blob/master/src/test/functional/java/com/sdl/demo/extjs3/form/SimpleForm.java
